### ISSUE TITLE
ERROR | Ejercicio 4

### ISSUE THREAD

**Issue by santivediap** [Guille-Rubio/Advanced-JS-map-filter-reduce#10]
Enunciado: Crea un segundo array result4 a partir del array numbers2 que devuelva solo los impares El array foodList2 devuelve el valor correcto

Hemos hecho el ejercicio como se pedía, colocando el siguiente código:
```
let numbers2 = [1,2,3,4,5,6,7,8,9,10];
const result4 = num => {
    return numbers2.filter(num => num % 2);
}
console.log(result4(numbers2));
```

Al hacer console.log de la variable, nos sale `(5) [1, 3, 5, 7, 9]`, el cual es el resultado que se pide en el ejercicio

**Comment by Guille-Rubio** [comment]
result4 en tu código es igual a una función, no realiza el cálculo si no la invocas. Si eliminas todo lo que hay entre el igual y el return te debería ir.

**Comment by santivediap** [comment]
Funciona perfectamente, gracias!
