### ISSUE TITLE
Fallo en test EJERCICIO 1 

### ISSUE THREAD

**Issue by aerozfx** [Guille-Rubio/Advanced-JS-map-filter-reduce#4]
En ese test hay errores, al esperar que `elevados` sea una función.
En el `Utiliza el método map` hay un `.not` que da problemas
<img width="1102" alt="Captura de pantalla 2023-05-08 a las 16 03 25" src="https://user-images.githubusercontent.com/118265607/236844873-ce290847-e72f-423a-9c72-a5cfb3f5cbc0.png">

**Comment by Guille-Rubio** [comment]
Hola Fernando, este test está escrito con una función para poder comprobar que se ha utilizado el método map para solucionarlo. Esto permite convertir la función en una string y comprobar si esta contiene el método map. Voy a cambiar el enunciado para que quede más claro, ¡Gracias!
