### ISSUE TITLE
FALLO en test 3

### ISSUE THREAD

**Issue by aerozfx** [Guille-Rubio/Advanced-JS-map-filter-reduce#5]
El test espera `Pepe es TheBoss` y el `objeto staff` incluye el rol `The Boss`.
Entra en conflicto con el test que espear que la clave `role` sea igual a `The Boss`
<img width="862" alt="Captura de pantalla 2023-05-08 a las 16 07 28" src="https://user-images.githubusercontent.com/118265607/236845762-ca562415-dada-42de-ba89-3258f5b0ec31.png">

**Comment by Guille-Rubio** [comment]
¡Corregido, gracias!
