### ISSUE TITLE
FALLO en test 6

### ISSUE THREAD

**Issue by aerozfx** [Guille-Rubio/Advanced-JS-map-filter-reduce#7]
Este test espera `Viaje a cancún` y el objeto `inventory` tiene el par clave valor de: `name`:`Viaje a Cancún`

<img width="509" alt="Captura de pantalla 2023-05-08 a las 16 11 09" src="https://user-images.githubusercontent.com/118265607/236846679-2f2a07a3-79fb-4a6b-b159-c55202800ec3.png">

**Comment by Guille-Rubio** [comment]
Corregido, thnx!
