### ISSUE TITLE
Fallo en test 7

### ISSUE THREAD

**Issue by aerozfx** [Guille-Rubio/Advanced-JS-map-filter-reduce#8]
Este test espera un `array` de 9 posiciones, sin opción a meter nuestro nombre.
Y luego el test espera que devuelva `Me llamo ${sentenceElements[2]} y quiero sentir la fuerza con javascript` en vez del nombre deseado

<img width="1097" alt="Captura de pantalla 2023-05-08 a las 16 12 57" src="https://user-images.githubusercontent.com/118265607/236847191-7bb4a52c-b0ab-4e67-8e6f-15c2583884c3.png">

**Comment by Guille-Rubio** [comment]
Corregido, thnx!
